config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from rest_framework import routers

from romain_sings.songs.urls import router as songs_router
from romain_sings.player import views as player_views

router = routers.DefaultRouter()
router.registry.extend(songs_router.registry)

urlpatterns = [
    path("", player_views.DashboardView.as_view(), name="home"),
    path('api/', include(router.urls)),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("romain_sings.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),

    path("songs/", include("romain_sings.songs.urls", namespace="songs")),


] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

romain_sings/songs/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from rest_framework import routers

from .views import SongViewSet, SongUploadView, AllSongsView, CardsSongsView


router = routers.DefaultRouter()
router.register(r'songs', SongViewSet)

app_name = "songs"

urlpatterns = [
    path("", view=AllSongsView.as_view(), name="list"),
    path("select", view=CardsSongsView.as_view(), name="cards"),

    path("upload/", view=SongUploadView.as_view(), name="upload"),

    # path("<uuid:song>/", view=SongDetailView.as_view(), name="detail"),
]

romain_sings/users/urls.py
from django.urls import path

from romain_sings.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

romain_sings/player/models.py
from django.db import models

from model_utils.models import TimeStampedModel


class PlayedEvent(TimeStampedModel):
    song = models.ForeignKey('songs.Song', null=True, blank=True, on_delete=models.CASCADE)

    class Meta:
        ordering = ('created',)

romain_sings/songs/models.py
# -*- coding: utf-8 -*-
from io import BytesIO
import os
import uuid

from django.conf import settings
from django.core.files.base import ContentFile
from django.core.files.storage import FileSystemStorage
from django.db import models
from django.utils.text import slugify

from model_utils.models import TimeStampedModel
import qrcode
import soco


media_storage = FileSystemStorage(location=str(settings.MEDIA_ROOT), base_url='/media')
sonos_storage = FileSystemStorage(location=str(settings.SONOS_BASE_DIR), base_url='/uploads')


def upload_to_sonos(instance, filename):
    return os.path.join(slugify(instance.artist), filename)


def qrcode_path(instance, filename):
    return os.path.join(str(instance.uuid), filename)


PLAY_SONG_IMMEDIATELY = 'play'
SMB_PROTOCOL = 'x-file-cifs'


class Song(TimeStampedModel):
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=255)
    artist = models.CharField(max_length=255, blank=True)
    illustration = models.ImageField(null=True, blank=True, upload_to=qrcode_path, storage=media_storage)
    qrcode = models.ImageField(null=True, blank=True, upload_to=qrcode_path, storage=media_storage)
    file = models.FileField(null=True, upload_to=upload_to_sonos, storage=sonos_storage)

    class Meta:
        ordering = ('-created', )

    @property
    def qr_id(self):
        return str(self.uuid.fields[0])

    def __str__(self):
        return '{}: {}'.format(self.artist, self.title)

    def build_qr(self, commit=True):
        img = qrcode.make('{}:{}'.format(PLAY_SONG_IMMEDIATELY, self.qr_id))
        buffer = BytesIO()
        img.save(buffer, format='PNG')
        file_content = ContentFile(buffer.getvalue())
        self.qrcode.save('qrcode.png', file_content)
        if commit:
            self.save()

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if not self.qrcode:
            self.build_qr(commit=True)

    @property
    def play_path(self):
        return '{}://{}{}'.format(SMB_PROTOCOL,
                                  settings.SONOS_MOUNT_HOSTNAME,
                                  settings.SONOS_BASE_DIR(str(self.file)))

    def play(self):
        current_device = settings.SONOS_ROOM_NAME
        spkr = soco.discovery.by_name(current_device).group.coordinator
        spkr.play_uri(self.play_path)


# TODO: modèle de statistiques de lecture
# TODO: carte album?

romain_sings/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

romain_sings/songs/forms.py
# -*- coding: utf-8 -*-
import binascii

from django import forms
from django.core.files.base import ContentFile

import mutagen

from .models import Song


class SongUploadForm(forms.ModelForm):

    class Meta:
        model = Song
        fields = ['file']

    def save(self, *args, **kwargs):
        file = self.cleaned_data['file']
        mfile = mutagen.File(file)

        if '©nam' in mfile:
            # mp4
            self.instance.title = mfile['©nam'][0]
            if '©ART' in mfile:
                self.instance.artist = mfile['©ART'][0]
            if 'covr' in mfile:
                mutagen_cover = mfile['covr'][0]
                if mutagen_cover.imageformat == mutagen_cover.FORMAT_JPEG:
                    extension = 'jpg'
                else:
                    extension = 'png'
                # mutagen_cover.hex returns hexadecimal represented as a string (!) e.g. 'af123b'
                file_content = ContentFile(binascii.unhexlify(mutagen_cover.hex()))
                self.instance.illustration.save('cover.{}'.format(extension), file_content)
        elif 'TIT2' in mfile:
            # mp3
            self.instance.title = mfile['TIT2'].text[0]
            if 'TPE1' in mfile:
                self.instance.artist = mfile['TPE1'][0]
            if 'APIC:' in mfile:
                # APIC files are jpeg stored as binary value.
                file_content = ContentFile(mfile['APIC:'].data)
                self.instance.illustration.save('cover.jpg', file_content)

        return super().save(*args, **kwargs)

romain_sings/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):

    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

romain_sings/player/views.py
from collections import OrderedDict
from datetime import timedelta

from django.db.models import Count, DateField
from django.views.generic import TemplateView
from django.db.models.functions import Trunc


from romain_sings.songs.models import Song
from .models import PlayedEvent


class DashboardView(TemplateView):
    template_name = "pages/dashboard.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_plays'] = PlayedEvent.objects.count()
        context['top5'] = PlayedEvent.objects.select_related('song')\
                                             .values('song', 'song__title')\
                                             .annotate(total_play=Count('id')).order_by('-total_play')[:5]
        context['total_songs'] = Song.objects.count()
        plays_per_day = PlayedEvent.objects.annotate(date=Trunc('created', 'day', output_field=DateField()))\
                                           .values('date')\
                                           .annotate(plays=Count('id'))\
                                           .order_by('date')
        plays_per_day_dict = OrderedDict((ppd['date'], ppd['plays']) for ppd in plays_per_day)
        min_date = next(iter(plays_per_day_dict))
        max_date = next(reversed(plays_per_day_dict))
        context['play_per_day_labels'] = [min_date] + [min_date + timedelta(days=i) for i
                                                       in range(0, (max_date-min_date).days)]
        context['play_per_day_values'] = [plays_per_day_dict.get(thedate, 0) for thedate
                                          in context['play_per_day_labels']]
        return context

romain_sings/songs/views.py
# -*- coding: utf-8 -*-
from rest_framework import viewsets

from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView

from .forms import SongUploadForm
from .models import Song
from .serializers import SongSerializer


class SongViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Song.objects.all()
    serializer_class = SongSerializer

    # todo: recherche par qr


class SongUploadView(CreateView):
    form_class = SongUploadForm
    template_name = 'songs/song_upload.html'
    success_url = reverse_lazy('songs:upload')


class AllSongsView(ListView):
    queryset = Song.objects.order_by('-created')
    template_name = "songs/songs_list.html"
    context_object_name = 'songs'


class CardsSongsView(ListView):
    template_name = "songs/songs.html"
    context_object_name = 'songs'

    def get_queryset(self):
        qs = Song.objects.all()
        if 's' in self.request.GET:
            songs = self.request.GET.getlist('s')
            qs = qs.filter(uuid__in=songs)
        if 'of' in self.request.GET:
            order_field = self.request.GET['of']
            if order_field in [field.name for field in Song._meta.get_fields()]:
                order_direction = self.request.GET.get('od', 'asc')
                if order_direction == 'desc':
                    qs = qs.order_by('-' + order_field)
                else:
                    qs = qs.order_by(order_field)
        else:
            qs = qs.order_by('-created')

        return qs

romain_sings/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserListView(LoginRequiredMixin, ListView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_list_view = UserListView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

romain_sings/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

romain_sings/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}Romain sings{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

  <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i,800" rel="stylesheet">

  {% block css %}
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
        integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
        crossorigin="anonymous">
  <link href="{% static 'css/project.css' %}" rel="stylesheet">
  {% endblock %}

</head>

<body class="materialdesign">

<div class="m-b-1 header-top-area">
  <div class="fixed-header-top">
    <nav class="navbar navbar-expand-md header-top-menu">
      <button class="navbar-toggler navbar-toggler-right" type="button"
              data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
              aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="container header-top-menu">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'songs:upload' %}">Upload song</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'songs:list' %}">All songs</a>
          </li>
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              {# URL provided by django-allauth/account/urls.py #}
              <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
            </li>
            <li class="nav-item">
              {# URL provided by django-allauth/account/urls.py #}
              <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
            </li>
          {% else %}

            <li class="nav-item">
              {# URL provided by django-allauth/account/urls.py #}
              <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
            </li>
          {% endif %}
        </ul>
        </div>
      </div>
    </nav>

  </div>

</div>


<div class="container">
<div class="breadcome-area mg-b-30 small-dn">
  {% if messages %}
    {% for message in messages %}
      <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
    {% endfor %}
  {% endif %}
</div>
<div class="mg-b-15">
  {% block content %}
    <p>Use this document as a way to quick start any new project.</p>
  {% endblock content %}
</div>



</div> <!-- /container -->

{% block modal %}{% endblock modal %}

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
{% block javascript %}

  <!-- Required by Bootstrap v4.1.1 -->
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"   integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="   crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

  <!-- Your stuff: Third-party javascript libraries go here -->


  <!-- place project specific Javascript in this file -->

  <script src="{% static 'js/project.js' %}"></script>


{% endblock javascript %}
</body>
</html>
 