config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from rest_framework import routers

from romain_sings.songs.urls import router as songs_router
from romain_sings.player import views as player_views

router = routers.DefaultRouter()
router.registry.extend(songs_router.registry)

urlpatterns = [
    path("", player_views.DashboardView.as_view(), name="home"),
    path('api/', include(router.urls)),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("romain_sings.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),

    path("songs/", include("romain_sings.songs.urls", namespace="songs")),


] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

romain_sings/songs/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from rest_framework import routers

from .views import SongViewSet, SongUploadView, AllSongsView, CardsSongsView


router = routers.DefaultRouter()
router.register(r'songs', SongViewSet)

app_name = "songs"

urlpatterns = [
    path("", view=AllSongsView.as_view(), name="list"),
    path("select", view=CardsSongsView.as_view(), name="cards"),

    path("upload/", view=SongUploadView.as_view(), name="upload"),

    # path("<uuid:song>/", view=SongDetailView.as_view(), name="detail"),
]

romain_sings/users/urls.py
from django.urls import path

from romain_sings.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

romain_sings/player/models.py
from django.db import models

from model_utils.models import TimeStampedModel


class PlayedEvent(TimeStampedModel):
    song = models.ForeignKey('songs.Song', null=True, blank=True, on_delete=models.CASCADE)

    class Meta:
        ordering = ('created',)

romain_sings/songs/models.py
# -*- coding: utf-8 -*-
from io import BytesIO
import os
import uuid

from django.conf import settings
from django.core.files.base import ContentFile
from django.core.files.storage import FileSystemStorage
from django.db import models
from django.utils.text import slugify

from model_utils.models import TimeStampedModel
import qrcode
import soco


media_storage = FileSystemStorage(location=str(settings.MEDIA_ROOT), base_url='/media')
sonos_storage = FileSystemStorage(location=str(settings.SONOS_BASE_DIR), base_url='/uploads')


def upload_to_sonos(instance, filename):
    return os.path.join(slugify(instance.artist), filename)


def qrcode_path(instance, filename):
    return os.path.join(str(instance.uuid), filename)


PLAY_SONG_IMMEDIATELY = 'play'
SMB_PROTOCOL = 'x-file-cifs'


class Song(TimeStampedModel):
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=255)
    artist = models.CharField(max_length=255, blank=True)
    illustration = models.ImageField(null=True, blank=True, upload_to=qrcode_path, storage=media_storage)
    qrcode = models.ImageField(null=True, blank=True, upload_to=qrcode_path, storage=media_storage)
    file = models.FileField(null=True, upload_to=upload_to_sonos, storage=sonos_storage)

    class Meta:
        ordering = ('-created', )

    @property
    def qr_id(self):
        return str(self.uuid.fields[0])

    def __str__(self):
        return '{}: {}'.format(self.artist, self.title)

    def build_qr(self, commit=True):
        img = qrcode.make('{}:{}'.format(PLAY_SONG_IMMEDIATELY, self.qr_id))
        buffer = BytesIO()
        img.save(buffer, format='PNG')
        file_content = ContentFile(buffer.getvalue())
        self.qrcode.save('qrcode.png', file_content)
        if commit:
            self.save()

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if not self.qrcode:
            self.build_qr(commit=True)

    @property
    def play_path(self):
        return '{}://{}{}'.format(SMB_PROTOCOL,
                                  settings.SONOS_MOUNT_HOSTNAME,
                                  settings.SONOS_BASE_DIR(str(self.file)))

    def play(self):
        current_device = settings.SONOS_ROOM_NAME
        spkr = soco.discovery.by_name(current_device).group.coordinator
        spkr.play_uri(self.play_path)


# TODO: modèle de statistiques de lecture
# TODO: carte album?

romain_sings/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

romain_sings/songs/forms.py
# -*- coding: utf-8 -*-
import binascii

from django import forms
from django.core.files.base import ContentFile

import mutagen

from .models import Song


class SongUploadForm(forms.ModelForm):

    class Meta:
        model = Song
        fields = ['file']

    def save(self, *args, **kwargs):
        file = self.cleaned_data['file']
        mfile = mutagen.File(file)

        if '©nam' in mfile:
            # mp4
            self.instance.title = mfile['©nam'][0]
            if '©ART' in mfile:
                self.instance.artist = mfile['©ART'][0]
            if 'covr' in mfile:
                mutagen_cover = mfile['covr'][0]
                if mutagen_cover.imageformat == mutagen_cover.FORMAT_JPEG:
                    extension = 'jpg'
                else:
                    extension = 'png'
                # mutagen_cover.hex returns hexadecimal represented as a string (!) e.g. 'af123b'
                file_content = ContentFile(binascii.unhexlify(mutagen_cover.hex()))
                self.instance.illustration.save('cover.{}'.format(extension), file_content)
        elif 'TIT2' in mfile:
            # mp3
            self.instance.title = mfile['TIT2'].text[0]
            if 'TPE1' in mfile:
                self.instance.artist = mfile['TPE1'][0]
            if 'APIC:' in mfile:
                # APIC files are jpeg stored as binary value.
                file_content = ContentFile(mfile['APIC:'].data)
                self.instance.illustration.save('cover.jpg', file_content)

        return super().save(*args, **kwargs)

romain_sings/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):

    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

romain_sings/player/views.py
from collections import OrderedDict
from datetime import timedelta

from django.db.models import Count, DateField
from django.views.generic import TemplateView
from django.db.models.functions import Trunc


from romain_sings.songs.models import Song
from .models import PlayedEvent


class DashboardView(TemplateView):
    template_name = "pages/dashboard.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_plays'] = PlayedEvent.objects.count()
        context['top5'] = PlayedEvent.objects.select_related('song')\
                                             .values('song', 'song__title')\
                                             .annotate(total_play=Count('id')).order_by('-total_play')[:5]
        context['total_songs'] = Song.objects.count()
        plays_per_day = PlayedEvent.objects.annotate(date=Trunc('created', 'day', output_field=DateField()))\
                                           .values('date')\
                                           .annotate(plays=Count('id'))\
                                           .order_by('date')
        plays_per_day_dict = OrderedDict((ppd['date'], ppd['plays']) for ppd in plays_per_day)
        min_date = next(iter(plays_per_day_dict))
        max_date = next(reversed(plays_per_day_dict))
        context['play_per_day_labels'] = [min_date] + [min_date + timedelta(days=i) for i
                                                       in range(0, (max_date-min_date).days)]
        context['play_per_day_values'] = [plays_per_day_dict.get(thedate, 0) for thedate
                                          in context['play_per_day_labels']]
        return context

romain_sings/songs/views.py
# -*- coding: utf-8 -*-
from rest_framework import viewsets

from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView

from .forms import SongUploadForm
from .models import Song
from .serializers import SongSerializer


class SongViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Song.objects.all()
    serializer_class = SongSerializer

    # todo: recherche par qr


class SongUploadView(CreateView):
    form_class = SongUploadForm
    template_name = 'songs/song_upload.html'
    success_url = reverse_lazy('songs:upload')


class AllSongsView(ListView):
    queryset = Song.objects.order_by('-created')
    template_name = "songs/songs_list.html"
    context_object_name = 'songs'


class CardsSongsView(ListView):
    template_name = "songs/songs.html"
    context_object_name = 'songs'

    def get_queryset(self):
        qs = Song.objects.all()
        if 's' in self.request.GET:
            songs = self.request.GET.getlist('s')
            qs = qs.filter(uuid__in=songs)
        if 'of' in self.request.GET:
            order_field = self.request.GET['of']
            if order_field in [field.name for field in Song._meta.get_fields()]:
                order_direction = self.request.GET.get('od', 'asc')
                if order_direction == 'desc':
                    qs = qs.order_by('-' + order_field)
                else:
                    qs = qs.order_by(order_field)
        else:
            qs = qs.order_by('-created')

        return qs

romain_sings/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserListView(LoginRequiredMixin, ListView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_list_view = UserListView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

romain_sings/templates/songs/card.inc.html
{% load staticfiles %}
<section class="song">
  <img src="{% if song.illustration %}{{ song.illustration.url }}{% else %}{% static "images/blank.png" %}{% endif %}"
       class="art"/>
  <img src="{{ song.qrcode.url }}" class="qrcode"/>
  <div class="labels">
    <h3>{{ song.title }}</h3>
    <p class="artist"><small>Par</small> {{ song.artist }}</p>
    {% if song.album %}<p class="album"><small>Dans</small> {{ song.album }}{% endif %}
  </div>
</section>

romain_sings/templates/songs/song_upload.html
{% extends "base.html" %}
{% load crispy_forms_tags i18n %}

{% block title %}{% trans "Add new song" %}{% endblock %}

{% block content %}
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="sparkline13-list shadow-reset">
          <div class="sparkline13-hd">
            <div class="main-sparkline13-hd">
              <h1>{% trans "Add new song" %}</h1>
            </div>
          </div>
          <div class="sparkline-content">
            <form class="form-horizontal" method="post" action="{% url 'songs:upload' %}" enctype="multipart/form-data">
              {% csrf_token %}
              {{ form|crispy }}
              <div class="control-group login-btn-inner">
                <div class="controls">
                  <button type="submit" class="btn btn-primary login-submit-cs">{% trans "Add" %}</button>
                </div>
              </div>
            </form>
            <div class="clearfix"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

romain_sings/templates/songs/songs.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Songs</title>
  <link href="https://fonts.googleapis.com/css?family=Raleway:400,700" rel="stylesheet">
    <link href="{% static 'css/card.css' %}" rel="stylesheet">
</head>
<body>
{% for song in songs %}
{% include "songs/card.inc.html" with song=song %}
{% endfor %}

</body>
</html>

romain_sings/templates/songs/songs_list.html
{% extends "base.html" %}
{% load crispy_forms_tags staticfiles humanize i18n datatables %}

{% block title %}{% trans "All songs available" %}{% endblock %}

{% block css %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css"
        href="https://cdn.datatables.net/v/bs4/dt-1.10.18/b-1.5.4/sl-1.2.6/datatables.min.css"/>
{% endblock %}

{% block javascript %}
  {{ block.super }}

  <script type="text/javascript"
          src="https://cdn.datatables.net/v/bs4/dt-1.10.18/b-1.5.4/sl-1.2.6/datatables.min.js"></script>
  <script>
    $(document).ready(function () {
      var table = $('#songs').DataTable({
        "language": {
          "url": "https://cdn.datatables.net/plug-ins/1.10.19/i18n/French.json" //"{{ STATIC_URL }}js/datatables/{{ LANGUAGE_CODE|datatable_i18n_url }}"
        },
        "ordering": true,
        "order": [[3, 'desc']],
        "columnDefs": [{"orderable": false, "targets": [0, 4]}],
        "lengthMenu": [[8, 16, 64, -1], [8, 16, 64, "{% trans "All" %}"]],
        "select": {"items": 'row', "style": 'multi'}

      });
      $orderField = $('#order-field');
      $orderDirection = $('#order-direction');

      table.on('order.dt', function () {
        var order = table.order();
        $orderDirection.val(order[0][1]);
        switch (order[0][0]) {
          case 1:
            orderValue = 'title';
            break;
          case 2:
            orderValue = 'artist';
            break;
          case 3:
            orderValue = 'created';
            break;
          default:
            orderValue = 'created';
        }
        $orderField.val(orderValue);
      });

      $('#cards-form').on("submit", function (event) {
        table.rows({selected: true}).nodes().each(function (row) {
          $('<input>').attr({
            type: 'hidden',
            name: 's',
            value: $(row).data('id')
          }).appendTo('form');
        });
      });
    });
  </script>
{% endblock %}


{% block content %}

  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="sparkline13-list shadow-reset">
          <div class="sparkline13-hd">
            <div class="main-sparkline13-hd">
              <h1>{% trans "All songs available" %}</h1>
            </div>
          </div>
          <div class="sparkline-content">
            <form method="GET" action="{% url 'songs:cards' %}" id="cards-form">
              <input type="hidden" id="order-field" name="of" value="created">
              <input type="hidden" id="order-direction" name="od" value="asc">
              <div class="login-btn-inner form-group-inner">
                <button type="submit" class="btn btn-primary login-submit-cs">{% trans "Print cards" %}</button>
              </div>

            </form>
            <hr>
            <div class="custom-datatable-overright">

              <table class="table" id="songs">
                <thead class="thead-dark">
                <tr>
                  <th></th>
                  <th>{% trans "Title" %}</th>
                  <th>{% trans "Artist" %}</th>
                  <th>{% trans "Added on" %}</th>
                  <th>{% trans "Actions" %}</th>
                </tr>
                </thead>
                <tbody>
                {% for song in songs %}
                  <tr data-id="{{ song.uuid }}">
                    <td {% if not song.illustration %}class="table-danger"{% endif %}>
                      {% if song.illustration %}<img src="{{ song.illustration.url }}" style="height:60px;"/>{% endif %}
                    </td>
                    <td>{{ song.title }}</td>
                    <td>{{ song.artist }}</td>
                    <td data-order="{{ song.created | date:"c" }}">{{ song.created|naturaltime }}</td>
                    <td></td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
              <div class="clearfix"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>



{% endblock %}